// Generated by gencpp from file formal_control/PathMsg.msg
// DO NOT EDIT!


#ifndef FORMAL_CONTROL_MESSAGE_PATHMSG_H
#define FORMAL_CONTROL_MESSAGE_PATHMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace formal_control
{
template <class ContainerAllocator>
struct PathMsg_
{
  typedef PathMsg_<ContainerAllocator> Type;

  PathMsg_()
    : header()
    , m()
    , y_start()
    , y_finish()
    , x_start()
    , x_finish()
    , check(false)  {
    }
  PathMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , m(_alloc)
    , y_start(_alloc)
    , y_finish(_alloc)
    , x_start(_alloc)
    , x_finish(_alloc)
    , check(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _m_type;
  _m_type m;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_start_type;
  _y_start_type y_start;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_finish_type;
  _y_finish_type y_finish;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_start_type;
  _x_start_type x_start;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_finish_type;
  _x_finish_type x_finish;

   typedef uint8_t _check_type;
  _check_type check;





  typedef boost::shared_ptr< ::formal_control::PathMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::formal_control::PathMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PathMsg_

typedef ::formal_control::PathMsg_<std::allocator<void> > PathMsg;

typedef boost::shared_ptr< ::formal_control::PathMsg > PathMsgPtr;
typedef boost::shared_ptr< ::formal_control::PathMsg const> PathMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::formal_control::PathMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::formal_control::PathMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace formal_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'formal_control': ['/home/gulce/final_ws/src/formal_control/msg', '/home/gulce/final_ws/src/formal_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::formal_control::PathMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::formal_control::PathMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::formal_control::PathMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::formal_control::PathMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::formal_control::PathMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::formal_control::PathMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::formal_control::PathMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aea262bd14c4beff32fb4111e598fc59";
  }

  static const char* value(const ::formal_control::PathMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaea262bd14c4beffULL;
  static const uint64_t static_value2 = 0x32fb4111e598fc59ULL;
};

template<class ContainerAllocator>
struct DataType< ::formal_control::PathMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "formal_control/PathMsg";
  }

  static const char* value(const ::formal_control::PathMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::formal_control::PathMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
float32[] m\n\
float32[] y_start\n\
float32[] y_finish\n\
float32[] x_start\n\
float32[] x_finish\n\
bool check\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::formal_control::PathMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::formal_control::PathMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.m);
      stream.next(m.y_start);
      stream.next(m.y_finish);
      stream.next(m.x_start);
      stream.next(m.x_finish);
      stream.next(m.check);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::formal_control::PathMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::formal_control::PathMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "m[]" << std::endl;
    for (size_t i = 0; i < v.m.size(); ++i)
    {
      s << indent << "  m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.m[i]);
    }
    s << indent << "y_start[]" << std::endl;
    for (size_t i = 0; i < v.y_start.size(); ++i)
    {
      s << indent << "  y_start[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y_start[i]);
    }
    s << indent << "y_finish[]" << std::endl;
    for (size_t i = 0; i < v.y_finish.size(); ++i)
    {
      s << indent << "  y_finish[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y_finish[i]);
    }
    s << indent << "x_start[]" << std::endl;
    for (size_t i = 0; i < v.x_start.size(); ++i)
    {
      s << indent << "  x_start[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x_start[i]);
    }
    s << indent << "x_finish[]" << std::endl;
    for (size_t i = 0; i < v.x_finish.size(); ++i)
    {
      s << indent << "  x_finish[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x_finish[i]);
    }
    s << indent << "check: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.check);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORMAL_CONTROL_MESSAGE_PATHMSG_H
