// Generated by gencpp from file robot_localization_243/GetState.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_243_MESSAGE_GETSTATE_H
#define ROBOT_LOCALIZATION_243_MESSAGE_GETSTATE_H

#include <ros/service_traits.h>


#include <robot_localization_243/GetStateRequest.h>
#include <robot_localization_243/GetStateResponse.h>


namespace robot_localization_243
{

struct GetState
{

typedef GetStateRequest Request;
typedef GetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetState
} // namespace robot_localization_243


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_243::GetState > {
  static const char* value()
  {
    return "b143410e9c7f7be208eedf8f691d8069";
  }

  static const char* value(const ::robot_localization_243::GetState&) { return value(); }
};

template<>
struct DataType< ::robot_localization_243::GetState > {
  static const char* value()
  {
    return "robot_localization_243/GetState";
  }

  static const char* value(const ::robot_localization_243::GetState&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_243::GetStateRequest> should match 
// service_traits::MD5Sum< ::robot_localization_243::GetState > 
template<>
struct MD5Sum< ::robot_localization_243::GetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_243::GetState >::value();
  }
  static const char* value(const ::robot_localization_243::GetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_243::GetStateRequest> should match 
// service_traits::DataType< ::robot_localization_243::GetState > 
template<>
struct DataType< ::robot_localization_243::GetStateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_243::GetState >::value();
  }
  static const char* value(const ::robot_localization_243::GetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_243::GetStateResponse> should match 
// service_traits::MD5Sum< ::robot_localization_243::GetState > 
template<>
struct MD5Sum< ::robot_localization_243::GetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_243::GetState >::value();
  }
  static const char* value(const ::robot_localization_243::GetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_243::GetStateResponse> should match 
// service_traits::DataType< ::robot_localization_243::GetState > 
template<>
struct DataType< ::robot_localization_243::GetStateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_243::GetState >::value();
  }
  static const char* value(const ::robot_localization_243::GetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_243_MESSAGE_GETSTATE_H
