// Generated by gencpp from file robot_localization_243/SetDatum.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_243_MESSAGE_SETDATUM_H
#define ROBOT_LOCALIZATION_243_MESSAGE_SETDATUM_H

#include <ros/service_traits.h>


#include <robot_localization_243/SetDatumRequest.h>
#include <robot_localization_243/SetDatumResponse.h>


namespace robot_localization_243
{

struct SetDatum
{

typedef SetDatumRequest Request;
typedef SetDatumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDatum
} // namespace robot_localization_243


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_243::SetDatum > {
  static const char* value()
  {
    return "fe903ca95d0210defda73a1629604439";
  }

  static const char* value(const ::robot_localization_243::SetDatum&) { return value(); }
};

template<>
struct DataType< ::robot_localization_243::SetDatum > {
  static const char* value()
  {
    return "robot_localization_243/SetDatum";
  }

  static const char* value(const ::robot_localization_243::SetDatum&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_243::SetDatumRequest> should match 
// service_traits::MD5Sum< ::robot_localization_243::SetDatum > 
template<>
struct MD5Sum< ::robot_localization_243::SetDatumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_243::SetDatum >::value();
  }
  static const char* value(const ::robot_localization_243::SetDatumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_243::SetDatumRequest> should match 
// service_traits::DataType< ::robot_localization_243::SetDatum > 
template<>
struct DataType< ::robot_localization_243::SetDatumRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_243::SetDatum >::value();
  }
  static const char* value(const ::robot_localization_243::SetDatumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_243::SetDatumResponse> should match 
// service_traits::MD5Sum< ::robot_localization_243::SetDatum > 
template<>
struct MD5Sum< ::robot_localization_243::SetDatumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_243::SetDatum >::value();
  }
  static const char* value(const ::robot_localization_243::SetDatumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_243::SetDatumResponse> should match 
// service_traits::DataType< ::robot_localization_243::SetDatum > 
template<>
struct DataType< ::robot_localization_243::SetDatumResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_243::SetDatum >::value();
  }
  static const char* value(const ::robot_localization_243::SetDatumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_243_MESSAGE_SETDATUM_H
