(cl:in-package formal_control-msg)
(cl:export '(HEADER-VAL
          HEADER
          RFDIST-VAL
          RFDIST
          LFDIST-VAL
          LFDIST
          BDIST-VAL
          BDIST
          V_RELATIVE-VAL
          V_RELATIVE
          ACTIONS-VAL
          ACTIONS
          POLICY-VAL
          POLICY
          OLD_POLICY-VAL
          OLD_POLICY
          V_EMG-VAL
          V_EMG
          YAW_REF-VAL
          YAW_REF
          GOT_NEW_PLAN-VAL
          GOT_NEW_PLAN
          EMERGENCY-VAL
          EMERGENCY
          CRIT_CHECK-VAL
          CRIT_CHECK
          CURRENT_STATE-VAL
          CURRENT_STATE
          LANE-VAL
          LANE
          TIMESTEP-VAL
          TIMESTEP
          REQUEST-VAL
          REQUEST
))